language: go

go:
  - 1.5

go_import_path: github.com/deis/makeup

install:
  - wget "https://github.com/Masterminds/glide/releases/download/0.8.3/glide-0.8.3-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-0.8.3-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH" GLIDE_HOME="$HOME/.glide"

script: make build
